### ISSUE TITLE
Does not run on CentOS 7 because it requires GLIBC_2.18

### ISSUE THREAD

**Issue by probonopd** [unruhschuh/Ipe.AppImage#1]
Please use an older distribution (e.g., CentOS 6) for building to ensure wider compatibility with older distributions.

This is what happens if I try to run the AppImage on **CentOS 7** CentOS-7.0-1406-x86_64-GnomeLive.iso:

```
[me@host ~]$ /run/initramfs/isoscan/Applications/Ipe-7.2.2.AppImage 
/run/initramfs/isoscan/Applications/Ipe-7.2.2.AppImage: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./lib/libstdc++.so.6)
```

If you do not want to use an older base system for building, then you might be interested in looking at https://github.com/probonopd/AppImageKit/tree/master/LibcWrapGenerator

**Comment by unruhschuh** [comment]
Fixed in the new AppImage at https://github.com/unruhschuh/Ipe.AppImage/releases/tag/v7.2.2

**Comment by probonopd** [comment]
I can confirm that it works on CentOS-7.0-1406-x86_64-GnomeLive.iso now. Thanks.
